
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VAL = 16;
  public static final int LIT_INT = 50;
  public static final int FIN_EXPR = 44;
  public static final int CHAR = 5;
  public static final int LIT_FLOAT = 49;
  public static final int DIFERENTE = 31;
  public static final int RESTA = 23;
  public static final int DIVISION_ENTERA = 21;
  public static final int INT = 2;
  public static final int FOR = 13;
  public static final int WRITE = 18;
  public static final int PRINCIPAL = 8;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int IGUAL = 30;
  public static final int OR = 35;
  public static final int BOOL = 4;
  public static final int INCREMENTO = 19;
  public static final int SUMA = 22;
  public static final int IF = 9;
  public static final int ID = 51;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int PAR_FIN = 41;
  public static final int DECREMENTO = 20;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int LIT_STRING = 48;
  public static final int MODULO = 26;
  public static final int MENOR = 32;
  public static final int LIT_CHAR = 47;
  public static final int PAR_INI = 40;
  public static final int BREAK = 15;
  public static final int VOID = 7;
  public static final int ASIGNACION = 37;
  public static final int MAYOR = 33;
  public static final int POTENCIA = 27;
  public static final int BLOQUE_FIN = 39;
  public static final int ELSE = 11;
  public static final int COR_FIN = 43;
  public static final int READ = 17;
  public static final int BLOQUE_INI = 38;
  public static final int WHILE = 12;
  public static final int MAYOR_IGUAL = 29;
  public static final int FLOAT = 3;
  public static final int COR_INI = 42;
  public static final int LIT_BOOL = 46;
  public static final int STRING = 6;
  public static final int MENOR_IGUAL = 28;
  public static final int DIVISION = 25;
  public static final int ELIF = 10;
  public static final int MULTIPLICACION = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "FLOAT",
  "BOOL",
  "CHAR",
  "STRING",
  "VOID",
  "PRINCIPAL",
  "IF",
  "ELIF",
  "ELSE",
  "WHILE",
  "FOR",
  "RETURN",
  "BREAK",
  "VAL",
  "READ",
  "WRITE",
  "INCREMENTO",
  "DECREMENTO",
  "DIVISION_ENTERA",
  "SUMA",
  "RESTA",
  "MULTIPLICACION",
  "DIVISION",
  "MODULO",
  "POTENCIA",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "IGUAL",
  "DIFERENTE",
  "MENOR",
  "MAYOR",
  "AND",
  "OR",
  "NOT",
  "ASIGNACION",
  "BLOQUE_INI",
  "BLOQUE_FIN",
  "PAR_INI",
  "PAR_FIN",
  "COR_INI",
  "COR_FIN",
  "FIN_EXPR",
  "COMA",
  "LIT_BOOL",
  "LIT_CHAR",
  "LIT_STRING",
  "LIT_FLOAT",
  "LIT_INT",
  "ID"
  };
}

